### ISSUE TITLE
Runtime and compute requirements

### ISSUE THREAD

**Issue by aditya-pola** [gkakogeorgiou/spot#2]
Hello,
Could you share more details about the single 24 GB gpu that was used?
I was also curious, what was the train-time for SPOT on different datasets (specifically COCO and PASCAL VOC). 
During the experimentation phase, did you train the models on smaller subsets or something like that to get an idea of the improvements?

**Comment by gkakogeorgiou** [comment]
Hi!

For each experiment, we trained the models using a single Quadro RTX 6000 or NVIDIA RTX A5000 GPU. For the COCO dataset, training took about 20 hours for the first 50 epochs of SPOT Stage-1 and 28 hours for the following 50 epochs in Stage-2. The training on the Pascal VOC dataset involved 560 epochs for each SPOT stage, which resulted in a similar overall training (maybe slightly shorter). We did not use smaller subsets for training during the experiments.

**Comment by aditya-pola** [comment]
Thank you for sharing!
